name: Generate llms.txt Files

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '*.md'
      - '.github/workflows/generate-llms-txt.yml'
  workflow_dispatch:
    inputs:
      input-directory:
        description: 'Input directory to process'
        required: false
        default: '.'
      test-mode:
        description: 'Run in test mode (use sample folder)'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate llms.txt files
        id: generate
        uses: ./.github/actions/llms-txt-generator
        with:
          input-directory: ${{ github.event.inputs.test-mode == 'true' && 'sample' || github.event.inputs.input-directory || '.' }}
          output-directory: ${{ github.event.inputs.test-mode == 'true' && 'sample' || '.' }}
          base-url: 'https://github.com/${{ github.repository }}/blob/main'
          project-name: ${{ github.event.inputs.test-mode == 'true' && 'Sample Documentation' || github.event.repository.name }}
          project-description: ${{ github.event.inputs.test-mode == 'true' && 'Test documentation from sample folder' || format('Documentation for {0}', github.event.repository.name) }}
          exclude-pattern: '**/node_modules/**,**/dist/**,**/.git/**'
          commit-changes: 'true'
          sections: |
            ${{ github.event.inputs.test-mode == 'true' && '{
              "Authentication": "sample/authentication/**",
              "Automation": "sample/automation/**",
              "Backend": "sample/backend/**",
              "Blueprint": "sample/blueprint/**",
              "Configuration": "sample/configuration/**",
              "Energy": "sample/energy/**",
              "Frontend": "sample/frontend/**",
              "Scene": "sample/scene/**",
              "Scripts": "sample/scripts/**",
              "Tools": "sample/tools/**",
              "Z-Wave": "sample/z-wave/**",
              "General": "sample/*.markdown"
            }' || '{
              "Docs": "docs/**",
              "Examples": "examples/**",
              "Guides": "guides/**"
            }' }}
      
      - name: Output generation results
        run: |
          echo "Files processed: ${{ steps.generate.outputs.files-processed }}"
          echo "llms.txt path: ${{ steps.generate.outputs.llms-txt-path }}"
          echo "llms-full.txt path: ${{ steps.generate.outputs.llms-full-txt-path }}"
